[package]
name = "yars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ['full'] }
warp = "0.3.2"
env_logger = "0.9.0"
log = "0.4.14"
tera = "1"